--- # Deploy

- name: Fetch stats on current deployment
  stat:
    path: "{{ current_path }}"
  register: current_path_stats

- name: Handle rollbacks
  import_tasks: rollbacks.yml
  when: current_path_stats.stat.islnk is defined and current_path_stats.stat.islnk
  tags: rollbacks

- name: Deploy
  import_tasks: deploy.yml
  tags: deploy
