---

domain: openfoodnetwork.ie
host_id: ie-prod
rails_env: production

mail_domain: openfoodnetwork.ie

enable_nginx_logging: true

certbot_domains:
  - www.openfoodnetwork.ie
  - openfoodnetwork.ie
